[database]
"hostname"="localhost"
"database"="block_research"
"username"="root"
"password"=""

[logger]
"log_dir"="./logger/logs"

[azure]
"storage_account_name"=""

"communication_services_endpoint"=""
"sender_email_address"=""